name: CESFW_conda
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.11=hd590300_1
  - anndata=0.10.3=pyhd8ed1ab_0
  - array-api-compat=1.7.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.1=py39h7633fee_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cython=3.0.10=py39h3d6467e_0
  - dbus=1.13.6=h5008d03_3
  - dill=0.3.8=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.52.4=py39hd3abc70_0
  - freetype=2.12.1=h267a509_2
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - h5py=3.9.0=nompi_py39h4dfffb9_100
  - harfbuzz=8.5.0=hfac3d4d_0
  - hdbscan=0.8.33=py39h44dd56e_4
  - hdf5=1.14.0=nompi_hb72d44e_103
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_1
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=20_linux64_openblas
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.6=default_h5d6823c_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.8.0=hca28451_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=13.2.0=h77fa898_7
  - libgcrypt=1.10.3=hd590300_0
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libglib=2.80.2=hf974151_0
  - libgomp=13.2.0=h77fa898_7
  - libgpg-error=1.49=h4f305b6_0
  - libhwloc=2.10.0=default_h5622ce7_1001
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=20_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.6=hb77312f_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.43=h2797004_0
  - libpq=16.3=ha72fbe1_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libsystemd0=255=h3516f8a_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.12.7=hc051c1a_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.42.0=py39h174d805_1
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib=3.8.2=py39hf3d152e_0
  - matplotlib-base=3.8.2=py39he9076e7_0
  - mpg123=1.32.6=h59595ed_0
  - multiprocess=0.70.15=py39hd1e30aa_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - natsort=8.4.0=pyhd8ed1ab_0
  - ncurses=6.5=h59595ed_0
  - nspr=4.35=h27087fc_0
  - nss=3.100=hca3bf56_0
  - numba=0.59.1=py39h615d6bd_0
  - numpy=1.23.5=py39h3d75532_0
  - openjpeg=2.5.2=h488ebb8_0
  - openpyxl=3.1.2=py39hd1e30aa_1
  - openssl=3.3.0=h4ab18f5_3
  - p-tqdm=1.4.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=1.5.3=py39h2ad29b5_1
  - pathos=0.3.2=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pillow=10.3.0=py39h90c7501_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - pooch=1.8.1=pyhd8ed1ab_0
  - pox=0.3.4=pyhd8ed1ab_0
  - ppft=1.7.6.8=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio-client=17.0=hb77b528_0
  - pynndescent=0.5.12=pyhca7485f_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.9=py39h52134e7_5
  - pyqt5-sip=12.12.2=py39h3d6467e_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=h0755675_0_cpython
  - python_abi=3.9=4_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - qt-main=5.15.8=hc9dc06e_21
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.5.0=py39h40c85ba_1
  - scipy=1.10.1=py39h6183b62_3
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - setuptools=70.0.0=pyhd8ed1ab_0
  - sip=6.7.12=py39h3d6467e_0
  - six=1.16.0=pyh6c4a22f_0
  - statsmodels=0.14.2=py39hd92a3bb_0
  - tbb=2021.12.0=h297d8ca_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4=py39hd1e30aa_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.41=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - anyio==4.0.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.13.1
    - beautifulsoup4==4.12.2
    - biomart==0.9.2
    - bleach==6.1.0
    - cffi==1.16.0
    - comm==0.2.2
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - fastjsonschema==2.18.1
    - fqdn==1.5.1
    - gseapy==1.1.0
    - importlib-metadata==7.1.0
    - ipykernel==6.29.4
    - ipython==8.18.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.2
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.6.2
    - jupyter-core==5.7.2
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.10.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.8
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.1
    - markupsafe==2.1.3
    - matplotlib-inline==0.1.7
    - mistune==3.0.2
    - nbclient==0.9.0
    - nbconvert==7.11.0
    - nbformat==5.9.2
    - nest-asyncio==1.6.0
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - overrides==7.4.0
    - pandocfilters==1.5.0
    - parso==0.8.4
    - pexpect==4.9.0
    - prometheus-client==0.18.0
    - prompt-toolkit==3.0.45
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.18.0
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pyyaml==6.0.1
    - pyzmq==26.0.3
    - referencing==0.30.2
    - remote-ikernel==0.4.6
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.12.0
    - send2trash==1.8.2
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.6.3
    - terminado==0.18.0
    - tinycss2==1.2.1
    - traitlets==5.14.3
    - types-python-dateutil==2.8.19.14
    - typing-extensions==4.12.1
    - umap-learn==0.5.6
    - uri-template==1.3.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - zipp==3.19.1
prefix: /relative_path/.conda/envs/CESFW_conda
