name: SCVI_conda
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.0.0=pyhd8ed1ab_0
  - alsa-lib=1.2.10=hd590300_0
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - ansiwrap=0.8.4=py_0
  - aom=3.7.1=h59595ed_0
  - arpack=3.8.0=nompi_h0baa96a_101
  - arrow=1.3.0=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - bbknn=1.6.0=py39hf95cd2a_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - black=24.1.1=py39hf3d152e_0
  - blessed=1.19.1=pyhe4f9e05_2
  - blosc=1.21.5=h0f2a231_0
  - boto3=1.33.8=pyhd8ed1ab_0
  - botocore=1.33.8=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py39h3d6467e_1
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.23.0=hd590300_0
  - c-blosc2=2.12.0=hb4ffafa_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cachecontrol=0.13.1=pyhd8ed1ab_0
  - cachecontrol-with-filecache=0.13.1=pyhd8ed1ab_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.16.0=py39h7a31438_0
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - chex=0.1.8=pyhd8ed1ab_0
  - cleo=2.1.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contextlib2=21.6.0=pyhd8ed1ab_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - croniter=1.3.15=pyhd8ed1ab_0
  - cryptography=41.0.7=py39he6105cc_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - cython=3.0.8=py39h3d6467e_0
  - dateutils=0.6.12=py_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - deepdiff=6.7.1=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - dm-tree=0.1.8=py39h60f6b12_2
  - docrep=0.3.2=pyh44b312d_0
  - dulwich=0.21.7=py39hd1e30aa_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - etils=1.5.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fa2=0.3.5=py39hb9d737c_2
  - fastapi=0.104.1=pyhd8ed1ab_0
  - filelock=3.13.1=pyhd8ed1ab_0
  - flax=0.7.5=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.46.0=py39hd1e30aa_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2023.12.1=pyhca7485f_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.2=hd590300_0
  - glib=2.78.2=hfc55251_0
  - glib-tools=2.78.2=hfc55251_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=h59595ed_0
  - gmpy2=2.1.2=py39h376b7d2_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.7=h8e1006c_0
  - gstreamer=1.22.7=h98fc4e7_0
  - h11=0.14.0=pyhd8ed1ab_0
  - harfbuzz=8.3.0=h3d44ed6_0
  - harmonypy=0.0.9=pyhdfd78af_0
  - hdf5=1.14.2=nompi_h4f84152_100
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - imagecodecs=2024.1.1=py39hf9b8f0e_0
  - imageio=2.36.1=pyh12aca89_1
  - importlib-metadata=7.0.0=pyha770c72_0
  - importlib-resources=6.1.1=pyhd8ed1ab_0
  - importlib_metadata=7.0.0=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - inquirer=3.1.4=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py39hf3d152e_0
  - jxrlib=1.1=hd590300_3
  - keyring=24.3.0=py39hf3d152e_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.2=h59595ed_1
  - libavif16=1.0.3=hed45d22_0
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=20_linux64_openblas
  - libclang=15.0.7=default_hb11cfb5_4
  - libclang13=15.0.7=default_ha2b6cf4_4
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.5.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt=1.10.3=hd590300_0
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libglib=2.78.2=h783c2da_0
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.47=h71f35ed_0
  - libgrpc=1.58.2=he06187c_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=20_linux64_openblas
  - libleidenalg=0.11.1=h00ab1b0_0
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm15=15.0.7=h5cf9203_3
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=16.1=hfc447b1_2
  - libprotobuf=4.24.3=hf27288f_1
  - libre2-11=2023.06.02=h7a70373_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libsystemd0=254=h3516f8a_0
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.6.0=h5d7e998_0
  - libxml2=2.11.6=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - libzopfli=1.0.3=h9c3ff4c_0
  - lightning=2.0.4=pyhd8ed1ab_0
  - lightning-cloud=0.5.57=pyhd8ed1ab_0
  - lightning-utilities=0.10.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py39hd1e30aa_1
  - matplotlib-base=3.9.4=py39h16632d1_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - ml-collections=0.1.1=pyhd8ed1ab_0
  - ml_dtypes=0.3.1=py39hddac248_2
  - more-itertools=10.1.0=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_0
  - mpg123=1.32.3=h59595ed_0
  - mpltern=1.0.4=pyhd8ed1ab_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.7=py39h7633fee_0
  - mudata=0.2.3=pyhd8ed1ab_0
  - multipledispatch=0.6.0=py_0
  - multiprocess=0.70.15=py39hd1e30aa_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - natsort=8.4.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - nspr=4.35=h27087fc_0
  - nss=3.95=h1d7d5a4_0
  - numpy=1.26.2=py39h474f0d3_0
  - numpyro=0.13.2=pyhd8ed1ab_1
  - openjpeg=2.5.0=h488ebb8_3
  - openpyxl=3.1.2=py39hd1e30aa_1
  - openssl=3.4.1=h7b32b05_0
  - opt-einsum=3.3.0=hd8ed1ab_2
  - opt_einsum=3.3.0=pyhc1e730c_2
  - optax=0.1.7=pyhd8ed1ab_0
  - orbax-checkpoint=0.4.4=pyhd8ed1ab_0
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - orjson=3.9.10=py39h10b2342_0
  - packaging=23.2=pyhd8ed1ab_0
  - papermill=2.4.0=pyhd8ed1ab_0
  - patchworklib=0.6.3=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - patsy=0.5.4=pyhd8ed1ab_0
  - pcre2=10.42=hcad00b1_0
  - pillow=10.1.0=py39had0adad_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - ply=3.11=py_1
  - poetry=1.7.1=linux_pyha804496_0
  - poetry-core=1.8.1=pyhd8ed1ab_0
  - poetry-plugin-export=1.6.0=pyhd8ed1ab_0
  - protobuf=4.24.3=py39h60f6b12_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio-client=16.1=hb77b528_5
  - pybind11-abi=4=hd8ed1ab_3
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.11=py39hd1e30aa_0
  - pydantic-core=2.14.5=py39h9fdd4d6_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pymde=0.1.18=py39h0f8d45d_1
  - pynndescent=0.5.11=pyhca7485f_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pyqt=5.15.9=py39h52134e7_5
  - pyqt5-sip=12.12.2=py39h3d6467e_5
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.8.6=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=h0755675_0_cpython
  - python-annoy=1.17.2=py39h3d6467e_1
  - python-build=1.0.3=pyhd8ed1ab_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python-fastjsonschema=2.19.0=pyhd8ed1ab_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python-ternary=1.0.8=pyhd8ed1ab_2
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytorch-lightning=2.1.1=pyhd8ed1ab_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywavelets=1.6.0=py39hd92a3bb_0
  - pyyaml=6.0.1=py39hd1e30aa_1
  - pyzmq=25.1.2=py39h8c080ef_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=h82b777d_17
  - rapidfuzz=3.5.2=py39h3d6467e_0
  - rav1e=0.6.6=he8a937b_2
  - re2=2023.06.02=h2873b5e_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rich=13.7.0=pyhd8ed1ab_0
  - s3transfer=0.8.2=pyhd8ed1ab_0
  - scikit-image=0.24.0=py39h3b40f6f_3
  - scikit-misc=0.1.4=py39hc77b598_4
  - scvi-tools=1.0.4=pyhd8ed1ab_0
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - secretstorage=3.3.3=py39hf3d152e_2
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - sip=6.7.12=py39h3d6467e_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sparse=0.14.0=pyhd8ed1ab_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - statsmodels=0.14.0=py39h44dd56e_2
  - stdlib-list=0.8.0=pyhd8ed1ab_0
  - svt-av1=1.7.0=h59595ed_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.10.0=h00ab1b0_2
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tensorstore=0.1.44=py39h5f15eca_3
  - texttable=1.7.0=pyhd8ed1ab_0
  - textwrap3=0.9.2=py_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tifffile=2024.6.18=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.3=pyha770c72_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchmetrics=1.2.1=pyhd8ed1ab_0
  - tornado=6.3.3=py39hd1e30aa_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.0=pyhd8ed1ab_0
  - trove-classifiers=2023.11.29=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - umap-learn=0.5.5=py39hf3d152e_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - upsetplot=0.8.0=pyhd8ed1ab_0
  - uvicorn=0.24.0.post1=py39hf3d152e_0
  - virtualenv=20.25.0=pyhd8ed1ab_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - websockets=11.0.3=py39hd1e30aa_1
  - wheel=0.42.0=pyhd8ed1ab_0
  - xarray=2023.11.0=pyhd8ed1ab_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.40=hd590300_0
  - xlrd=1.2.0=pyh9f0ad1d_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h59595ed_0
  - zfp=1.0.1=h5888daf_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.5=hfc55251_0
  - pip:
    - anndata==0.10.7
    - anyio==4.1.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - array-api-compat==1.6
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.13.1
    - biomart==0.9.2
    - bleach==6.1.0
    - cattrs==23.2.3
    - chart-studio==1.1.0
    - clinc==0.1.2
    - comm==0.2.0
    - contourpy==1.2.1
    - cykhash==2.0.1
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - ete3==3.1.3
    - executing==2.0.1
    - fastcluster==1.2.6
    - fqdn==1.5.1
    - future==1.0.0
    - get-annotations==0.1.2
    - gseapy==1.1.1
    - h5py==3.11.0
    - hmmlearn==0.3.0
    - igraph==0.11.5
    - iniconfig==2.0.0
    - ipykernel==6.27.1
    - ipython==8.18.1
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jax==0.4.19
    - jaxlib==0.4.19
    - jedi==0.19.1
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.2
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-core==5.5.0
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.1
    - jupyter-server==2.12.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.9
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.2
    - jupyterlab-widgets==3.0.9
    - kaleido==0.2.1
    - legacy-api-wrap==1.4
    - leidenalg==0.10.2
    - llvmlite==0.42.0
    - macs3==3.0.1
    - matplotlib==3.8.4
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - mizani==0.11.4
    - nbclient==0.9.0
    - nbconvert==7.12.0
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - numba==0.59.1
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.1.105
    - overrides==7.4.0
    - pandas==2.1.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.9.0
    - platformdirs==4.1.0
    - plotly==5.19.0
    - plotnine==0.13.6
    - pluggy==1.4.0
    - polars==0.19.19
    - pooch==1.8.1
    - prometheus-client==0.19.0
    - prompt-toolkit==3.0.41
    - psutil==5.9.6
    - pure-eval==0.2.2
    - pyarrow==15.0.0
    - pybiomart==0.2.0
    - pyfaidx==0.7.2.2
    - pyfish==1.0.3
    - pysankey==0.0.1
    - pytest==8.0.0
    - python-json-logger==2.0.7
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - referencing==0.31.1
    - remote-ikernel==0.4.6
    - requests-cache==1.2.0
    - retrying==1.3.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.13.2
    - rustworkx==0.14.1
    - scanpy==1.10.1
    - scikit-learn==1.4.2
    - scipy==1.12.0
    - send2trash==1.8.2
    - setcoverpy==0.9.1
    - snapatac2==2.5.3
    - stack-data==0.6.3
    - terminado==0.18.0
    - tinycss2==1.2.1
    - torch==2.3.0
    - torchvision==0.18.0
    - triton==2.3.0
    - uri-template==1.3.0
    - url-normalize==1.4.3
    - urllib3==2.1.0
    - webcolors==1.13
    - webencodings==0.5.1
    - widgetsnbextension==4.0.9
prefix: /relative_path/.conda/envs/SCVI_conda
